Update analyzer, refactor code, and add abstract class support
Litee/moq.analyzers pull request #20
Opened 2024-05-30 20:31 UTC by rjmurillo

This commit includes several updates and improvements. The `ConstructorArgumentsShouldMatchAnalyzerTests.ShouldFailIfClassParametersDoNotMatch.approved.txt` file has been updated to reflect changes in the source code. The `FooAbstract` class and its usage have been removed from `ConstructorArgumentsShouldMatch.cs`. Defensive programming practices have been added to `DiagnosticVerifier.Helper.cs` to ensure non-null arguments. A new file `AbstractClass.cs` has been added to `Moq.Analyzers.Test.csproj`. The `Analyze` method in `ConstructorArgumentsShouldMatchAnalyzer.cs` has been refactored for better readability and maintainability, and now supports abstract classes. The `Moq.Analyzers.csproj` now uses the latest C# language version and the assembly version has been updated to `0.0.6.0`. New test class `AbstractClassTests` and related files have been added to verify the functionality of the updated analyzer.

Fixes #1

2024-05-30 20:34 UTC, rjmurillo commented
@MattKotsenas the build action introduced in #9 didn't run on this PR

2024-05-30 20:41 UTC, MattKotsenas commented
> @MattKotsenas the build action introduced in #9 didn't run on this PR

Copy/paste error on my part. The default branch is `master` and my code uses `main`.

Will update to master until we have the ability to change the default branch.

2024-05-30 20:49 UTC, MattKotsenas commented
Actions issue is fixed in #21.

2024-05-31 18:43 UTC, rjmurillo commented
This is failing between platforms. On Windows and through Ubuntu in WSL, the line numbers are a certain value. On a stand alone Ubuntu VM, they're about 50 lines off. 

```diff
Diagnostic 2
	Id: Moq1300
-	Location: SourceFile(Test0.cs[1594..1604))
+	Location: SourceFile(Test0.cs[1534..1544))
	Highlight: OtherClass
	Lines: mock.As<OtherClass>();
	Severity: Error
	Message: Mock.As() should take interfaces only
```

Still looking into this

2024-05-31 22:21 UTC, MattKotsenas requested changes

2024-05-31 22:21 UTC, MattKotsenas commented on Source/Moq.Analyzers.Test/Data/AbstractClass.Bad.cs
> +        private void TestBad()
From conversation, some test cases missing:

- Pass an argument to a constructor that takes no arguments
- Pass (string, int) to a constructor that takes (int, string) or equivalent test
- Pass the incorrect number of arguments to constructor

2024-05-31 23:05 UTC, MattKotsenas approved these changes

2024-05-31 23:06 UTC, merged